name: CMake on a single platform

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Update & Install G++15
      run: sudo /usr/bin/bash build-gcc-15.sh

    - name: Build
      working-directory: ${{github.workspace}}
      run: /usr/bin/bash ./build.sh

    - name: Install
      working-directory: ${{github.workspace}}
      run: sudo /usr/bin/bash ./install.sh

    - name: Test
      working-directory: ${{github.workspace}}
      run: /usr/bin/bash ./test.sh

    - name: Uninstall
      working-directory: ${{github.workspace}}
      run: sudo /usr/bin/bash ./uninstall.sh

