name: CMake on a single platform

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Update & Install G++15
      run: apt update && apt install gcc g++

    - name: Build
      working-directory: ${{github.workspace}}
      run: ./build.sh

    - name: Install
      working-directory: ${{github.workspace}}
      run: sudo ./install.sh

    - name: Test
      working-directory: ${{github.workspace}}
      run: ./test.sh

    - name: Uninstall
      working-directory: ${{github.workspace}}
      run: sudo ./uninstall.sh

